### ISSUE TITLE
Order data structure implementation

### ISSUE THREAD

**Issue by last1here** [mmu-acgjn/Advanced_Web_Dev_Project#17]
Implement the model for the order entity.

```
 {
        "id": "5",
        "order_items": [
            {
                "menu_item_id": "323232dsds",
                "name": "Some dish",
                "price_per_portion": 2.22,
                "quantity": 2
            }
        ],
        "table_id": 1,
        "status": "In Progress",
        "finished_order_time": "2019-02-01T15:58:27.541+0000"
    }
```

**Comment by chloe-hodgson** [comment]
Is the `finished_order_time` the time that the order was completed? Should we also record the "start" time (`order_time`?) so that we can display that in the kitchen view?

**Comment by chloe-hodgson** [comment]
Ignore last comment, just seen your most recent commit

**Comment by last1here** [comment]
Yeah, that’s for the whole order. If we want to be able to add items to the order at a later point each item might need to track its ‘addedAt’ datetime.

Probably want to add finishedAt also for both the order and items, I’ll add this tomorrow.
