### ISSUE TITLE
Staff database

### ISSUE THREAD

**Issue by jessicawong217** [mmu-acgjn/Advanced_Web_Dev_Project#34]
role = {"Waiter", "Manager", "Kitchen"}

staff = 
[
  {
    firstname: Jo,
    surname: Smith,
    role: 'Waiter'
  }
]

**Comment by jessicawong217** [comment]
public staff = [
        {
            firstname: 'Klaus',
            surname: 'Logan',
            role: 'Waiter'
        },
        {
            firstname: 'Susanne',
            surname: 'Smith',
            role: 'Waiter'
        },
        {
            firstname: 'Joanne',
            surname: 'Lee',
            role: 'Manager'
        },
        {
            firstname: 'John',
            surname: 'McGregor',
            role: 'Manager'
        },
        {
            firstname: 'Lucy',
            surname: 'McCabe',
            role: 'Kitchen'
        },
        {
            firstname: 'James',
            surname: 'Peter',
            role: 'Kitchen'
        },
        {
            firstname: 'Amanda',
            surname: 'Hogen',
            role: 'Waiter'
        },
        {
            firstname: 'Lewis',
            surname: 'Marino',
            role: 'Waiter'
        }
    ];

**Comment by last1here** [comment]
I’ll add a pin for login also.
